sudo: false

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache

language: scala

scala:
  - "2.11.12"
  - "2.12.10"
  - "2.13.1"

jdk:
  - openjdk8

script:
  - sbt "++${TRAVIS_SCALA_VERSION}!" test test:doc mimaReportBinaryIssues

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -exec rm {} +
  - find $HOME/.ivy2 -name "ivydata-*.properties" -exec rm {} +

matrix:
  include:
  - sudo: required
    scala: SCALA_NATIVE
    before_install:
    - curl https://raw.githubusercontent.com/scala-native/scala-native/cddb41c2ded4da4/scripts/travis_setup.sh | bash -x
    script:
    - sbt coreNative/test examplesNative/test
