sudo: false

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache

language: scala

scala:
  - "2.10.6"
  - "2.11.8"
  - "2.12.0-RC2"

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test mima-report-binary-issues

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -exec rm {} +
  - find $HOME/.ivy2 -name "ivydata-*.properties" -exec rm {} +
